#!/usr/bin/env bash
#A  Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /var/run/myscript.pid
function handle_sigterm {
    echo "I hate the kill command"
}
function handle_sigint {
    echo "Y U no love me?!"
}

function handle_sigquit {
    rm /var/run/myscript.pid
    exit 0
}
# Register signal handlers
trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

# Loop forever
while true
do
    echo "To infinity and beyond"
    sleep 1
done
